#!/usr/bin/env node
/* build-site.js — assemble the Netlify publish directory from an explicit
 * allowlist. Run after gen-config.js.
 *
 * WHY THIS EXISTS (and why redirect rules were not enough)
 * Publishing the repo root exposed every internal file: design docs, specs,
 * build scripts, the reference/ College Board PDFs. Redirect rules in
 * netlify.toml looked like they fixed it, but measured against the live site:
 *
 *     /tests/injection-proof.js  -> 404   (redirect matched)
 *     /TESTS/injection-proof.js  -> 200   (file served!)
 *
 * Netlify matches redirect `from` paths CASE-SENSITIVELY while serving files
 * CASE-INSENSITIVELY. A blocklist therefore cannot work: every rule is
 * bypassable by changing capitalisation, and an n-character path has 2^n
 * variants. The only robust fix is deny-by-default — don't put the files in
 * the publish directory at all. Nothing here can be reached by any URL in any
 * capitalisation, because it simply is not deployed.
 *
 * Adding a file the app needs? Add it to ALLOW below. The build fails if
 * index.html references something that is not on the list, so a forgotten
 * entry surfaces as a red build rather than a 404 in a student's browser.
 */
"use strict";
const fs = require("fs");
const path = require("path");

const OUT = "_site";

/* Everything the running app requires — and nothing else. */
const ALLOW = [
  "index.html",
  "404.html",
  "styles.css",
  "app.js",
  "attempts.js",
  "dashboard.js",
  "grading.js",
  "render.js",
  "test-data.js",
  "config.js",    // generated by gen-config.js, which must run first
  "_headers"      // only takes effect inside the publish directory
];

function die(lines){
  console.error("\n==================================================");
  console.error(" BUILD FAILED — publish directory not assembled");
  console.error("==================================================");
  lines.forEach(l => console.error(" " + l));
  console.error("");
  process.exit(1);
}

/* --- every local asset index.html asks for must be allowlisted --- */
let html = "";
try{ html = fs.readFileSync("index.html", "utf8"); }
catch(e){ die(["index.html is missing from the checkout."]); }

const referenced = [];
const re = /(?:src|href)\s*=\s*"([^"]+)"/g;
let m;
while((m = re.exec(html)) !== null){
  const v = m[1];
  if(/^(https?:)?\/\//i.test(v) || v.startsWith("data:") || v.startsWith("#")) continue;
  referenced.push(v.replace(/^\.?\//, ""));
}
const missingFromAllow = referenced.filter(r => ALLOW.indexOf(r) === -1);
if(missingFromAllow.length){
  die(["index.html references files that are not in build-site.js ALLOW:",
       "  " + missingFromAllow.join(", "),
       "Add them to ALLOW (or drop the reference) and rebuild.",
       "Without this the deploy would 404 them in students' browsers."]);
}

/* --- assemble --- */
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const copied = [], absent = [];
for(const name of ALLOW){
  if(!fs.existsSync(name)){ absent.push(name); continue; }
  fs.copyFileSync(name, path.join(OUT, name));
  copied.push(name);
}
if(absent.length){
  die(["These allowlisted files are missing from the checkout: " + absent.join(", "),
       absent.indexOf("config.js") !== -1
         ? "config.js is generated by gen-config.js — it must run before this script."
         : "Check the repository contents."]);
}

/* --- prove the result contains nothing else --- */
const shipped = fs.readdirSync(OUT).sort();
const unexpected = shipped.filter(f => ALLOW.indexOf(f) === -1);
if(unexpected.length) die(["Unexpected files in " + OUT + ": " + unexpected.join(", ")]);

console.log("build-site.js: publish directory " + OUT + "/ contains " + shipped.length + " file(s):");
shipped.forEach(f => console.log("  " + f));
console.log("  -> everything else in the repo (docs, specs, build scripts,");
console.log("     reference/, supabase/, tests/) is NOT deployed.");
