#!/usr/bin/env node
/* build-site.js — assemble the Netlify publish directory from an explicit
 * allowlist. Run after gen-config.js.
 *
 * WHY THIS EXISTS (and why redirect rules were not enough)
 * Publishing the repo root exposed every internal file: design docs, specs,
 * build scripts, the reference/ College Board PDFs. Redirect rules in
 * netlify.toml looked like they fixed it, but measured against the live site:
 *
 *     /tests/injection-proof.js  -> 404   (redirect matched)
 *     /TESTS/injection-proof.js  -> 200   (file served!)
 *
 * Netlify matches redirect `from` paths CASE-SENSITIVELY while serving files
 * CASE-INSENSITIVELY. A blocklist therefore cannot work: every rule is
 * bypassable by changing capitalisation, and an n-character path has 2^n
 * variants. The only robust fix is deny-by-default — don't put the files in
 * the publish directory at all. Nothing here can be reached by any URL in any
 * capitalisation, because it simply is not deployed.
 *
 * Adding a file the app needs? Add it to ALLOW below. The build fails if
 * index.html references something that is not on the list, so a forgotten
 * entry surfaces as a red build rather than a 404 in a student's browser.
 */
"use strict";
const fs = require("fs");
const path = require("path");

const OUT = "_site";

/* Everything the running app requires — and nothing else. */
const ALLOW = [
  "index.html",
  "404.html",
  "styles.css",
  "app.js",
  "attempts.js",
  "dashboard.js",
  "grading.js",
  "render.js",
  "skilldomains.js",
  "testdata/manifest.js",
  "testdata/archive/index.js",   // which superseded builds exist (tiny, startup)
  "config.js",    // generated by gen-config.js, which must run first
  "_headers"      // only takes effect inside the publish directory
];

function die(lines){
  console.error("\n==================================================");
  console.error(" BUILD FAILED — publish directory not assembled");
  console.error("==================================================");
  lines.forEach(l => console.error(" " + l));
  console.error("");
  process.exit(1);
}

/* --- every local asset index.html asks for must be allowlisted --- */
let html = "";
try{ html = fs.readFileSync("index.html", "utf8"); }
catch(e){ die(["index.html is missing from the checkout."]); }

const referenced = [];
const re = /(?:src|href)\s*=\s*"([^"]+)"/g;
let m;
while((m = re.exec(html)) !== null){
  const v = m[1];
  if(/^(https?:)?\/\//i.test(v) || v.startsWith("data:") || v.startsWith("#")) continue;
  referenced.push(v.replace(/^\.?\//, ""));
}
const missingFromAllow = referenced.filter(r => ALLOW.indexOf(r) === -1);
if(missingFromAllow.length){
  die(["index.html references files that are not in build-site.js ALLOW:",
       "  " + missingFromAllow.join(", "),
       "Add them to ALLOW (or drop the reference) and rebuild.",
       "Without this the deploy would 404 them in students' browsers."]);
}

/* --- assemble --- */
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const copied = [], absent = [];
for(const name of ALLOW){
  if(!fs.existsSync(name)){ absent.push(name); continue; }
  const dest = path.join(OUT, name);
  fs.mkdirSync(path.dirname(dest), { recursive: true });   // allows testdata/x.js
  fs.copyFileSync(name, dest);
  copied.push(name);
}

/* Every test in the manifest ships. These are fetched at runtime rather than
   referenced from index.html, so the reference scan above cannot see them —
   the manifest is the list of what must exist, and a test named there but
   missing from disk would 404 mid-sitting. Fail the build instead. */
const TESTDATA_DIR = "testdata";
let manifestIds = [];
try{
  const mf = fs.readFileSync(path.join(TESTDATA_DIR, "manifest.js"), "utf8");
  const ids = mf.match(/"testId"\s*:\s*"([^"]+)"/g) || [];
  manifestIds = ids.map(s => s.replace(/.*"testId"\s*:\s*"/, "").replace(/"$/, ""));
}catch(e){
  die(["testdata/manifest.js is missing or unreadable — the app cannot start without it."]);
}
if(!manifestIds.length) die(["testdata/manifest.js lists no tests."]);
const missingTests = manifestIds.filter(id => !fs.existsSync(path.join(TESTDATA_DIR, id + ".js")));
if(missingTests.length){
  die(["Tests listed in the manifest have no testdata file: " + missingTests.join(", "),
       "A student starting one of these would hit a 404 mid-sitting."]);
}
fs.mkdirSync(path.join(OUT, TESTDATA_DIR), { recursive: true });
manifestIds.forEach(id => {
  const rel = path.join(TESTDATA_DIR, id + ".js");
  fs.copyFileSync(rel, path.join(OUT, rel));
  copied.push(rel);
});

/* Every ARCHIVED build the index lists ships too — Review Mode and resume
   pin attempts to the build they were sat on, and a listed-but-missing file
   would 404 exactly where the student expects their review. The index and
   the files on disk must agree in BOTH directions; drift means someone
   changed testdata/archive/ by hand — run `node archive-testdata.js`. */
const ARCHIVE_DIR = path.join(TESTDATA_DIR, "archive");
let archiveFiles = [];
try{
  const ix = fs.readFileSync(path.join(ARCHIVE_DIR, "index.js"), "utf8");
  const m = ix.match(/window\.TEST_ARCHIVE_INDEX\s*=\s*(\{[\s\S]*?\});/);
  if(!m) die(["testdata/archive/index.js is unparseable — run `node archive-testdata.js`."]);
  const idx = JSON.parse(m[1].replace(/,\s*}/g, "}"));
  archiveFiles = Object.keys(idx).sort().reduce((acc, id) =>
    acc.concat(idx[id].map(ver => id + "@" + ver + ".js")), []);
}catch(e){
  die(["testdata/archive/index.js is missing or unreadable: " + e.message,
       "Run `node archive-testdata.js` and commit its output."]);
}
const onDisk = fs.readdirSync(ARCHIVE_DIR)
  .filter(f => f.endsWith(".js") && f !== "index.js").sort();
const unlisted = onDisk.filter(f => archiveFiles.indexOf(f) === -1);
const missingArchives = archiveFiles.filter(f => !fs.existsSync(path.join(ARCHIVE_DIR, f)));
if(unlisted.length || missingArchives.length){
  die([].concat(
    missingArchives.length ? ["testdata/archive/index.js lists builds with no file: " + missingArchives.join(", ")] : [],
    unlisted.length ? ["testdata/archive/ has builds the index doesn't list: " + unlisted.join(", ")] : [],
    ["The archive and its index have drifted — run `node archive-testdata.js` and commit."]));
}
fs.mkdirSync(path.join(OUT, ARCHIVE_DIR), { recursive: true });
archiveFiles.forEach(f => {
  const rel = path.join(ARCHIVE_DIR, f);
  fs.copyFileSync(rel, path.join(OUT, rel));
  copied.push(rel);
});
if(absent.length){
  die(["These allowlisted files are missing from the checkout: " + absent.join(", "),
       absent.indexOf("config.js") !== -1
         ? "config.js is generated by gen-config.js — it must run before this script."
         : "Check the repository contents."]);
}

/* --- prove the result contains nothing else --- */
function walk(dir, base){
  return fs.readdirSync(dir).reduce((acc, f) => {
    const full = path.join(dir, f);
    const rel = base ? base + "/" + f : f;
    return acc.concat(fs.statSync(full).isDirectory() ? walk(full, rel) : [rel]);
  }, []);
}
const shipped = walk(OUT, "").sort();
// allowlisted outright, a manifest-listed test, or an index-listed archived
// build — all deliberately copied above
const permitted = ALLOW.concat(manifestIds.map(id => TESTDATA_DIR + "/" + id + ".js"))
  .concat(archiveFiles.map(f => TESTDATA_DIR + "/archive/" + f));
const unexpected = shipped.filter(f => permitted.indexOf(f) === -1);
if(unexpected.length) die(["Unexpected files in " + OUT + ": " + unexpected.join(", ")]);

console.log("build-site.js: publish directory " + OUT + "/ contains " + shipped.length + " file(s):");
shipped.forEach(f => console.log("  " + f));
console.log("  -> everything else in the repo (docs, specs, build scripts,");
console.log("     reference/, supabase/, tests/) is NOT deployed.");
