/* testdata/archive/index.js — which superseded builds are archived.
   Generated by archive-testdata.js — do not hand-edit. Loaded at startup
   (it is tiny); the archived builds themselves lazy-load exactly like
   current test files, only when a pinned attempt opens. */
window.TEST_ARCHIVE_INDEX = {
 "202503usv1": ["2026-08-14-a", "2026-08-14-b", "2026-08-14-c"],
 "202503usv2": ["2026-08-15-a"],
 "202506asiav2": ["2026-08-13-a"],
 "202508asiav1": ["2026-08-11-a"],
 "202509asiav2": ["2026-08-17-a"],
 "202509asiav4": ["2026-08-12-a", "2026-08-13-a"],
 "202510usv3": ["2026-08-08-a", "2026-08-08-b", "2026-08-09-a"],
 "202511asiav1": ["2026-08-05-a"],
 "202603asiav1": ["2026-08-06-a"],
 "202606asiav1": ["2026-08-01-c", "2026-08-09-a"],
 "202606asiav2": ["2026-08-01-a", "2026-08-02-a", "2026-08-02-b", "2026-08-09-a"]
};
