/* testdata/bank-index.js — the question index the set builder consumes:
   one entry per bank question (retired included, flagged) with subject,
   skill, tags, key type and a stem preview, so custom practice sets can be
   assembled without fetching any bank's full file. Regenerated by
   export_bank.py; entries for form questions may join in a later pass
   (containerType distinguishes them). */
window.BANK_INDEX = {
 "indexVersion": 1,
 "questionCount": 1,
 "activeCount": 1,
 "entries": [
  {
   "ref": "bank-david-core:q0001",
   "containerType": "bank",
   "bankId": "bank-david-core",
   "qid": "q0001",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "algebra",
    "linear-equations"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 3(x-4)=18, what is the value of x?"
  }
 ]
};
