/* testdata/bank-index.js — the question index the set builder consumes:
   one entry per bank question (retired included, flagged) with subject,
   skill, tags, key type and a stem preview, so custom practice sets can be
   assembled without fetching any bank's full file. Regenerated by
   export_bank.py; entries for form questions may join in a later pass
   (containerType distinguishes them). */
window.BANK_INDEX = {
 "indexVersion": 1,
 "questionCount": 206,
 "activeCount": 188,
 "entries": [
  {
   "ref": "bank-202608-salvage:q0001",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0001",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav1:m1-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Maya bought stickers and granola bars for $ 145. Each package of stickers cost…"
  },
  {
   "ref": "bank-202608-salvage:q0002",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0002",
   "subject": "math",
   "skill": "Circles",
   "tags": [
    "src:202608asiav1:m1-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the length, in millimeters, of segment BC?"
  },
  {
   "ref": "bank-202608-salvage:q0003",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0003",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m1-q13"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0188",
   "stemPreview": "What is the x coordinate of the x- intercept of line k?"
  },
  {
   "ref": "bank-202608-salvage:q0004",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0004",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m1-q14"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0199",
   "stemPreview": "An equation of the graph shown is y = (-3/8) (x - p)² + 6, where p is an intege…"
  },
  {
   "ref": "bank-202608-salvage:q0005",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0005",
   "subject": "math",
   "skill": "Linear inequalities in one or two variables",
   "tags": [
    "src:202608asiav1:m1-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "To cut a lawn, Jamal charges a fee of $ 18.00 for his equipment and $ 8.75 per…"
  },
  {
   "ref": "bank-202608-salvage:q0006",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0006",
   "subject": "math",
   "skill": "Right triangles and trigonometry",
   "tags": [
    "src:202608asiav1:m1-q17"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0200",
   "stemPreview": "In triangle PQR, the sine of angle Q is 1/2. What is the length of PQ?"
  },
  {
   "ref": "bank-202608-salvage:q0007",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0007",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m1-q18"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0189",
   "stemPreview": "Which function gives the number of points awarded for a correct answer x second…"
  },
  {
   "ref": "bank-202608-salvage:q0008",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0008",
   "subject": "math",
   "skill": "Systems of two linear equations in two variables",
   "tags": [
    "src:202608asiav1:m1-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the given system of equations, a and b are constants. The graphs of these eq…"
  },
  {
   "ref": "bank-202608-salvage:q0009",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0009",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav1:m1-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 7 + x = 1, what is the value of -22- 2x?"
  },
  {
   "ref": "bank-202608-salvage:q0010",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0010",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav1:m1-q21"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0190",
   "stemPreview": "Which equation correctly expresses v in terms of t and w?"
  },
  {
   "ref": "bank-202608-salvage:q0011",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0011",
   "subject": "math",
   "skill": "Linear functions",
   "tags": [
    "src:202608asiav1:m1-q22"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0191",
   "stemPreview": "The table shows three values of x and their corresponding values of gx, where g…"
  },
  {
   "ref": "bank-202608-salvage:q0012",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0012",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav1:m1-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression gives the area of the square?"
  },
  {
   "ref": "bank-202608-salvage:q0013",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0013",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav1:m1-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the value of x?"
  },
  {
   "ref": "bank-202608-salvage:q0014",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0014",
   "subject": "math",
   "skill": "Percentages",
   "tags": [
    "src:202608asiav1:m1-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What percentage of the soccer players at the camp are midfielders?"
  },
  {
   "ref": "bank-202608-salvage:q0015",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0015",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m1-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which statement is the best interpretation of S (3) =315?"
  },
  {
   "ref": "bank-202608-salvage:q0016",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0016",
   "subject": "math",
   "skill": "One-variable data: Distributions and measures of center and spread",
   "tags": [
    "src:202608asiav1:m2-q1"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0192",
   "stemPreview": "The table shows the frequency of each data value in a data set. Which data valu…"
  },
  {
   "ref": "bank-202608-salvage:q0017",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0017",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav1:m2-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 5- 3x = 48, what is the value of (1/6)(5- 3x)?"
  },
  {
   "ref": "bank-202608-salvage:q0018",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0018",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav1:m2-q12"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0201",
   "stemPreview": "In the figure, lines m and n are parallel and line t intersects both lines. Wha…"
  },
  {
   "ref": "bank-202608-salvage:q0019",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0019",
   "subject": "math",
   "skill": "Probability and conditional probability",
   "tags": [
    "src:202608asiav1:m2-q14"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0193",
   "stemPreview": "If a sandwich is selected at random, which expression represents the probabilit…"
  },
  {
   "ref": "bank-202608-salvage:q0020",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0020",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m2-q15"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0194",
   "stemPreview": "What is the value of h(4)?"
  },
  {
   "ref": "bank-202608-salvage:q0021",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0021",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m2-q16"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0195",
   "stemPreview": "What is the slope of line k?"
  },
  {
   "ref": "bank-202608-salvage:q0022",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0022",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav1:m2-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which value is a solution to the given equation?"
  },
  {
   "ref": "bank-202608-salvage:q0023",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0023",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m2-q20"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0196",
   "stemPreview": "What was the population of this city in 1742?"
  },
  {
   "ref": "bank-202608-salvage:q0024",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0024",
   "subject": "math",
   "skill": "Percentages",
   "tags": [
    "src:202608asiav1:m2-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A scientist studied the effects of mixing two chemicals, chemical A and chemica…"
  },
  {
   "ref": "bank-202608-salvage:q0025",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0025",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m2-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which equation represents this situation?"
  },
  {
   "ref": "bank-202608-salvage:q0026",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0026",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav1:m2-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What value of p is the solution to the given equation?"
  },
  {
   "ref": "bank-202608-salvage:q0027",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0027",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m2-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "How many feet from the marker will the train be 6 seconds after passing the mar…"
  },
  {
   "ref": "bank-202608-salvage:q0028",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0028",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav1:m2-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "At a particular restaurant, the total cost of 6 chicken wings and a salad is 15…"
  },
  {
   "ref": "bank-202608-salvage:q0029",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0029",
   "subject": "math",
   "skill": "Ratios, rates, proportional relationships, and units",
   "tags": [
    "src:202608asiav1:m2-q7"
   ],
   "keyType": "spr",
   "retired": true,
   "supersededBy": "q0197",
   "stemPreview": "A certain salmon shark can swim at a maximum speed of 16 meters per second. At…"
  },
  {
   "ref": "bank-202608-salvage:q0030",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0030",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav1:m2-q9"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0198",
   "stemPreview": "Which expression is equivalent to 240x² + 56?"
  },
  {
   "ref": "bank-202608-salvage:q0031",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0031",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav1:rw1-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical and precise word or phras…"
  },
  {
   "ref": "bank-202608-salvage:q0032",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0032",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw1-q10"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0202",
   "stemPreview": "According to the graph, the lowest-priced nuts were _____ Which choice most eff…"
  },
  {
   "ref": "bank-202608-salvage:q0033",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0033",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw1-q12"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0203",
   "stemPreview": "Which consideration, if true, should make the farmer most hesitant to rely on w…"
  },
  {
   "ref": "bank-202608-salvage:q0034",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0034",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav1:rw1-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0035",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0035",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav1:rw1-q16"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0036",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0036",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav1:rw1-q17"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0037",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0037",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav1:rw1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0038",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0038",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav1:rw1-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0039",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0039",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav1:rw1-q23"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0040",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0040",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav1:rw1-q24"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to say how sponges and sea squirts are the same. Which choice…"
  },
  {
   "ref": "bank-202608-salvage:q0041",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0041",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav1:rw1-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize the order in which Frances E. Allen and John McC…"
  },
  {
   "ref": "bank-202608-salvage:q0042",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0042",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav1:rw1-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical and precise word or phras…"
  },
  {
   "ref": "bank-202608-salvage:q0043",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0043",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav1:rw1-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best describes the overall structure of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0044",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0044",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw2-q10"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0204",
   "stemPreview": "Which choice most effectively uses data from the table to complete the statemen…"
  },
  {
   "ref": "bank-202608-salvage:q0045",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0045",
   "subject": "rw",
   "skill": "Command of Evidence (Textual)",
   "tags": [
    "src:202608asiav1:rw2-q11"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which finding, if true, would most strongly support the researchers’ conclusion?"
  },
  {
   "ref": "bank-202608-salvage:q0046",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0046",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav1:rw2-q14"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0047",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0047",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav1:rw2-q17"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0048",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0048",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav1:rw2-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0049",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0049",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav1:rw2-q24"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0050",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0050",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav1:rw2-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between the two classical compositi…"
  },
  {
   "ref": "bank-202608-salvage:q0051",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0051",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav1:rw2-q26"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between Moreno and Mensah. Which ch…"
  },
  {
   "ref": "bank-202608-salvage:q0052",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0052",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav1:rw2-q27"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most effectively uses information from the given sentences to spec…"
  },
  {
   "ref": "bank-202608-salvage:q0053",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0053",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav1:rw2-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best states the main purpose of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0054",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0054",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav1:rw2-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best states the main purpose of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0055",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0055",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav1:rw2-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Based on the text, what does Tom most likely believe about Martin?"
  },
  {
   "ref": "bank-202608-salvage:q0056",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0056",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav2:m1-q1"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A right square prism has a height of 10 units. The volume of the prism is 160 c…"
  },
  {
   "ref": "bank-202608-salvage:q0057",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0057",
   "subject": "math",
   "skill": "Right triangles and trigonometry",
   "tags": [
    "src:202608asiav2:m1-q14"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In triangle PQR, the sine of ∠Q is 1/2. What is the length of segment PQ?"
  },
  {
   "ref": "bank-202608-salvage:q0058",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0058",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav2:m1-q15"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the xy-plane, line k passes through the points (6, 5) and (7, 11) and is def…"
  },
  {
   "ref": "bank-202608-salvage:q0059",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0059",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav2:m1-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 9x+3=34, what is the value of 2(9x+3)?"
  },
  {
   "ref": "bank-202608-salvage:q0060",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0060",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav2:m1-q22"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Each side of equilateral triangle R is multiplied by a scale factor of k to cre…"
  },
  {
   "ref": "bank-202608-salvage:q0061",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0061",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav2:m1-q3"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The function f is defined by f(x) = 2x^{2} - 3x. What is the value of f(6)?"
  },
  {
   "ref": "bank-202608-salvage:q0062",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0062",
   "subject": "math",
   "skill": "Circles",
   "tags": [
    "src:202608asiav2:m1-q4"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the xy-plane, what is the radius of the circle defined by (x + 2)^{2} + (y +…"
  },
  {
   "ref": "bank-202608-salvage:q0063",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0063",
   "subject": "math",
   "skill": "Systems of two linear equations in two variables",
   "tags": [
    "src:202608asiav2:m1-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "At what point (x, y) do the graphs of the equations y = 9 and y = -2x + 7 inter…"
  },
  {
   "ref": "bank-202608-salvage:q0064",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0064",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav2:m2-q12"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "3rx + 5 = 12x + 9 In the given equation, r is a constant. The equation has no s…"
  },
  {
   "ref": "bank-202608-salvage:q0065",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0065",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav2:m2-q13"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Spheres A and B have a point of tangency at point P, where segment MP is a diam…"
  },
  {
   "ref": "bank-202608-salvage:q0066",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0066",
   "subject": "math",
   "skill": "Circles",
   "tags": [
    "src:202608asiav2:m2-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Circle A (shown) is defined by the equation (x + 2)^{2} + y^{2} = 9. Circle B (…"
  },
  {
   "ref": "bank-202608-salvage:q0067",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0067",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m2-q20"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "x + 33 = √(x + 45) - 12 The solutions to the given equation are s and t, where…"
  },
  {
   "ref": "bank-202608-salvage:q0068",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0068",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav2:m2-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "For an online trivia game, 300 points are awarded for a correct answer if a que…"
  },
  {
   "ref": "bank-202608-salvage:q0069",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0069",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav2:m2-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression is equivalent to (x² - 19x + 70)/(x² - 25), where x > 5?"
  },
  {
   "ref": "bank-202608-salvage:q0070",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0070",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav2:m2-q22"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the figure, AB, DE, and CF are parallel. If 202° < x + y + z < 215 °, which…"
  },
  {
   "ref": "bank-202608-salvage:q0071",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0071",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav2:m2-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression is equivalent to 5/(x - 8) + 5/(x - 8)², where x > 8?"
  },
  {
   "ref": "bank-202608-salvage:q0072",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0072",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav2:m2-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The height of a right circular cylinder is 47 inches, and the circumference of…"
  },
  {
   "ref": "bank-202608-salvage:q0073",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0073",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608asiav3:m1-q13"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "How many solutions does the equation 7x + 3x + 12 = 10x + 5 + 7 have?"
  },
  {
   "ref": "bank-202608-salvage:q0074",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0074",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav3:m1-q14"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A right square prism has a height of 5 units. The volume of the prism is 405 cu…"
  },
  {
   "ref": "bank-202608-salvage:q0075",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0075",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav3:m1-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "During the month of January, an airport parking garage is offering a special pr…"
  },
  {
   "ref": "bank-202608-salvage:q0076",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0076",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav3:m1-q17"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "For x = 0, y has a value of 190. The value of y increases by 20% for every incr…"
  },
  {
   "ref": "bank-202608-salvage:q0077",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0077",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav3:m1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "(5x + 10)(2x + 1) - (3x - 18) For all values of x, the given expression is equi…"
  },
  {
   "ref": "bank-202608-salvage:q0078",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0078",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav3:m1-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The measures of the interior angles of triangle ABC are 34°, 68°, and x°. What…"
  },
  {
   "ref": "bank-202608-salvage:q0079",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0079",
   "subject": "math",
   "skill": "Ratios, rates, proportional relationships, and units",
   "tags": [
    "src:202608asiav3:m1-q4"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A certain great white shark can swim at a maximum speed of 15 meters per second…"
  },
  {
   "ref": "bank-202608-salvage:q0080",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0080",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav3:m1-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A right square pyramid has a base edge length of 3 centimeters and a height of…"
  },
  {
   "ref": "bank-202608-salvage:q0081",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0081",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav3:m1-q7"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "An equation of the graph shown is y = (1/4) (x - p)² + 4, where p is an integer…"
  },
  {
   "ref": "bank-202608-salvage:q0082",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0082",
   "subject": "math",
   "skill": "Percentages",
   "tags": [
    "src:202608asiav3:m1-q9"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The price of an item increased by p% from $18 to $21. What is the value of p?"
  },
  {
   "ref": "bank-202608-salvage:q0083",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0083",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav3:m2-q14"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "y = 3x^{3} + 8 y = 363x + 8 A solution to the given system of equations is (x,…"
  },
  {
   "ref": "bank-202608-salvage:q0084",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0084",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav3:m2-q16"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In right triangle ABC, angle C is the right angle and BC = 17. Point D lies on…"
  },
  {
   "ref": "bank-202608-salvage:q0085",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0085",
   "subject": "math",
   "skill": "Right triangles and trigonometry",
   "tags": [
    "src:202608asiav3:m2-q22"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A rectangle is inscribed in a circle such that the diagonal of the rectangle is…"
  },
  {
   "ref": "bank-202608-salvage:q0086",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0086",
   "subject": "math",
   "skill": "Two-variable data: Models and scatterplots",
   "tags": [
    "src:202608asiav3:m2-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The scatterplot shows the relationship between two variables, x and y. Which of…"
  },
  {
   "ref": "bank-202608-salvage:q0087",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0087",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav3:m2-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression is equivalent to (x² - 10x + 21)/((x - 7)(x + 7)), where x > 7?"
  },
  {
   "ref": "bank-202608-salvage:q0088",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0088",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav3:m2-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "60x^{2}+60x=-10 One solution to the given equation can be written as x=(-6-k√(3…"
  },
  {
   "ref": "bank-202608-salvage:q0089",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0089",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw1-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0090",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0090",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw1-q12"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0091",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0091",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav3:rw1-q14"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0092",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0092",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav3:rw1-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0093",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0093",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav3:rw1-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0094",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0094",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav3:rw1-q23"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between Andrade and Adesina. Which…"
  },
  {
   "ref": "bank-202608-salvage:q0095",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0095",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav3:rw1-q24"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between the two classical compositi…"
  },
  {
   "ref": "bank-202608-salvage:q0096",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0096",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav3:rw1-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "As used in the text, what does the word “traces” most nearly mean?"
  },
  {
   "ref": "bank-202608-salvage:q0097",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0097",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav3:rw1-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best describes the overall structure of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0098",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0098",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav3:rw1-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Common name Average mass (kg) Capable of flight? Which choice most effectively…"
  },
  {
   "ref": "bank-202608-salvage:q0099",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0099",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw1-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0100",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0100",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw1-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0101",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0101",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav3:rw2-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical and precise word or phras…"
  },
  {
   "ref": "bank-202608-salvage:q0102",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0102",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav3:rw2-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0103",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0103",
   "subject": "rw",
   "skill": "Central Ideas and Details",
   "tags": [
    "src:202608asiav3:rw2-q22"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best states the main idea of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0104",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0104",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav3:rw2-q26"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0105",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0105",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav3:rw2-q27"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0106",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0106",
   "subject": "rw",
   "skill": "Cross-Text Connections",
   "tags": [
    "src:202608asiav3:rw2-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Text 1 Text 2 Based on the texts, how would the author of Text 2 most likely re…"
  },
  {
   "ref": "bank-202608-salvage:q0107",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0107",
   "subject": "math",
   "skill": "Right triangles and trigonometry",
   "tags": [
    "src:202608asiav4:m1-q14"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In right triangle PQR, angle R is a right angle, PR = 36, and sin Q = 1/2. What…"
  },
  {
   "ref": "bank-202608-salvage:q0108",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0108",
   "subject": "math",
   "skill": "Systems of two linear equations in two variables",
   "tags": [
    "src:202608asiav4:m1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A proposal for a construction project was included on a city election ballot. A…"
  },
  {
   "ref": "bank-202608-salvage:q0109",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0109",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m1-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If √ (x-6)=7, what is the value of (x-6)?"
  },
  {
   "ref": "bank-202608-salvage:q0110",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0110",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m1-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "x^{2} + 22x = -121 What is the solution to the given equation?"
  },
  {
   "ref": "bank-202608-salvage:q0111",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0111",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav4:m1-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Kaden owns a business that makes signs. The equation t = 18s + 15 gives the tot…"
  },
  {
   "ref": "bank-202608-salvage:q0112",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0112",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav4:m1-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The length of each side of a square is 68 inches. Which expression gives the ar…"
  },
  {
   "ref": "bank-202608-salvage:q0113",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0113",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m2-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "w = 19 1 = (w - 19)^{2}/25 + (p + 3)^{2}/49 A solution to the given system of e…"
  },
  {
   "ref": "bank-202608-salvage:q0114",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0114",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608asiav4:m2-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The height of a right circular cylinder is 31 inches, and the circumference of…"
  },
  {
   "ref": "bank-202608-salvage:q0115",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0115",
   "subject": "math",
   "skill": "Inference from sample statistics and margin of error",
   "tags": [
    "src:202608asiav4:m2-q14"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "From a population of 30,000 people, 3,000 were chosen at random and surveyed ab…"
  },
  {
   "ref": "bank-202608-salvage:q0116",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0116",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m2-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The graph of a system of a linear equation and a quadratic equation is shown. A…"
  },
  {
   "ref": "bank-202608-salvage:q0117",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0117",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav4:m2-q16"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "An initial mixture consists of 300 grams of metal X and 20 grams of metal Y. Du…"
  },
  {
   "ref": "bank-202608-salvage:q0118",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0118",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav4:m2-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In a certain region, the population of Phasianus colchicus is estimated each ye…"
  },
  {
   "ref": "bank-202608-salvage:q0119",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0119",
   "subject": "math",
   "skill": "Area and volume",
   "tags": [
    "src:202608usv1:m2-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A sphere is inscribed in a right circular cylinder, as shown. The sphere touche…"
  },
  {
   "ref": "bank-202608-salvage:q0120",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0120",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav4:m2-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A researcher agitated a quantity of milk inside a graduated beaker, which produ…"
  },
  {
   "ref": "bank-202608-salvage:q0121",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0121",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav4:m2-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the triangle shown, z = 32 °. Which of the following represents y in terms o…"
  },
  {
   "ref": "bank-202608-salvage:q0122",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0122",
   "subject": "math",
   "skill": "Percentages",
   "tags": [
    "src:202608asiav4:m2-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A scientist studied the effects of mixing two chemicals, chemical A and chemica…"
  },
  {
   "ref": "bank-202608-salvage:q0123",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0123",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608asiav4:m2-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "(1/3) x^{2} + 58 = t + 4 In the given equation, t is a constant. The equation h…"
  },
  {
   "ref": "bank-202608-salvage:q0124",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0124",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav4:rw1-q11"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Based on the text, what can be inferred about Macduff Circle?"
  },
  {
   "ref": "bank-202608-salvage:q0125",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0125",
   "subject": "rw",
   "skill": "Command of Evidence (Textual)",
   "tags": [
    "src:202608asiav4:rw1-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which quotation from Cane most effectively illustrates the claim?"
  },
  {
   "ref": "bank-202608-salvage:q0126",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0126",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav4:rw1-q16"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Film name Visible light allowed through Glare reduction Based on the window-fil…"
  },
  {
   "ref": "bank-202608-salvage:q0127",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0127",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav4:rw1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0128",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0128",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav4:rw1-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0129",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0129",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav4:rw1-q24"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0130",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0130",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav4:rw1-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between the two classical compositi…"
  },
  {
   "ref": "bank-202608-salvage:q0131",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0131",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608asiav4:rw1-q26"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize the order in which Shafi Goldwasser and Maurice…"
  },
  {
   "ref": "bank-202608-salvage:q0132",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0132",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav4:rw1-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical and precise word or phras…"
  },
  {
   "ref": "bank-202608-salvage:q0133",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0133",
   "subject": "rw",
   "skill": "Command of Evidence (Textual)",
   "tags": [
    "src:202608asiav4:rw1-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which quotation from a historian best supports the student’s claim?"
  },
  {
   "ref": "bank-202608-salvage:q0134",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0134",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav4:rw1-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Based on the text, what can most reasonably be inferred about Ramchand?"
  },
  {
   "ref": "bank-202608-salvage:q0135",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0135",
   "subject": "rw",
   "skill": "Central Ideas and Details",
   "tags": [
    "src:202608asiav4:rw2-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best reflects the researchers’ conclusions?"
  },
  {
   "ref": "bank-202608-salvage:q0136",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0136",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav4:rw2-q23"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Highly Traveled Commercial Airline Routes in 2017–18 Location Distance 2018 201…"
  },
  {
   "ref": "bank-202608-salvage:q0137",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0137",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav4:rw2-q24"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Examples of Hoards Found in Scotland and Wales Hoard name Date of contents Year…"
  },
  {
   "ref": "bank-202608-salvage:q0138",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0138",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav4:rw2-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0139",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0139",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav4:rw2-q26"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0140",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0140",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608asiav4:rw2-q27"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0141",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0141",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav4:rw2-q5"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best states the main purpose of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0142",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0142",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav4:rw2-q6"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best states the main purpose of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0143",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0143",
   "subject": "rw",
   "skill": "Text Structure and Purpose",
   "tags": [
    "src:202608asiav4:rw2-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best describes the overall structure of the text?"
  },
  {
   "ref": "bank-202608-salvage:q0144",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0144",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "src:202608usv1:m1-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 6 - 5x = 48, what is the value of (1/6)(6 - 5x)?"
  },
  {
   "ref": "bank-202608-salvage:q0145",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0145",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608usv1:m1-q14"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "During the month of May, an airport parking garage is offering a special price…"
  },
  {
   "ref": "bank-202608-salvage:q0146",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0146",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608usv1:m1-q15"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The population of a certain city doubled every 75 years from 1659 to 1959. The…"
  },
  {
   "ref": "bank-202608-salvage:q0147",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0147",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608usv1:m1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The graph shows the height above ground, in meters, of a ball x seconds after t…"
  },
  {
   "ref": "bank-202608-salvage:q0148",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0148",
   "subject": "math",
   "skill": "Linear inequalities in one or two variables",
   "tags": [
    "src:202608usv1:m1-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The shaded region shown represents the solutions to which inequality?"
  },
  {
   "ref": "bank-202608-salvage:q0149",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0149",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608usv1:m1-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression is equivalent to 210x² + 80?"
  },
  {
   "ref": "bank-202608-salvage:q0150",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0150",
   "subject": "math",
   "skill": "Percentages",
   "tags": [
    "src:202608usv1:m1-q7"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "45 is p% of 125. What is the value of p?"
  },
  {
   "ref": "bank-202608-salvage:q0151",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0151",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608usv1:m2-q11"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A machine launches a baseball from ground level. The baseball reaches a maximum…"
  },
  {
   "ref": "bank-202608-salvage:q0152",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0152",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608usv1:m2-q13"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the figure, line r is parallel to line s, and line t intersects both lines.…"
  },
  {
   "ref": "bank-202608-salvage:q0153",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0153",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608usv1:m2-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "x y -16 -46 5 38 The table shows two values of x and their corresponding values…"
  },
  {
   "ref": "bank-202608-salvage:q0154",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0154",
   "subject": "math",
   "skill": "Linear inequalities in one or two variables",
   "tags": [
    "src:202608usv1:m2-q2"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The shaded region shown represents the solutions to which inequality? 18 y 16 1…"
  },
  {
   "ref": "bank-202608-salvage:q0155",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0155",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608usv1:m2-q4"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "w = 14 1 = (w - 19)^{2}/25 + (p + 3)^{2}/49 A solution to the given system of e…"
  },
  {
   "ref": "bank-202608-salvage:q0156",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0156",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608usv1:m2-q7"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "For all values of x, the given expression is equivalent to which of the followi…"
  },
  {
   "ref": "bank-202608-salvage:q0157",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0157",
   "subject": "math",
   "skill": "Nonlinear equations in one variable and systems of equations in two variables",
   "tags": [
    "src:202608usv1:m2-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "48x^{2} + 48x = -3 One solution to the given equation can be written as x = (-6…"
  },
  {
   "ref": "bank-202608-salvage:q0158",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0158",
   "subject": "math",
   "skill": "Systems of two linear equations in two variables",
   "tags": [
    "src:202608usv1:m2-q9"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Line j in the xy-plane passes through the points (7, 0) and (0, 4). Line k pass…"
  },
  {
   "ref": "bank-202608-salvage:q0159",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0159",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608usv1:rw1-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0160",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0160",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608usv1:rw1-q13"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0161",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0161",
   "subject": "rw",
   "skill": "Transitions",
   "tags": [
    "src:202608usv1:rw1-q22"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical transition?"
  },
  {
   "ref": "bank-202608-salvage:q0162",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0162",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608usv1:rw1-q23"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The student wants to emphasize a similarity between cherries and strawberries.…"
  },
  {
   "ref": "bank-202608-salvage:q0163",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0163",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608usv1:rw1-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most effectively uses information from the given sentences to intr…"
  },
  {
   "ref": "bank-202608-salvage:q0164",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0164",
   "subject": "rw",
   "skill": "Rhetorical Synthesis",
   "tags": [
    "src:202608usv1:rw1-q26"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most effectively uses information from the given sentences to emph…"
  },
  {
   "ref": "bank-202608-salvage:q0165",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0165",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608usv1:rw2-q12"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0166",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0166",
   "subject": "rw",
   "skill": "Central Ideas and Details",
   "tags": [
    "src:202608usv1:rw2-q23"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice best captures St. Ogg’s as it is presented by the narrator in the…"
  },
  {
   "ref": "bank-202608-salvage:q0167",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0167",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m2-q11"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which of the following is an equation of the resulting graph?"
  },
  {
   "ref": "bank-202608-salvage:q0168",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0168",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav1:rw1-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0169",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0169",
   "subject": "rw",
   "skill": "Words in Context",
   "tags": [
    "src:202608asiav1:rw2-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text with the most logical and precise word or phras…"
  },
  {
   "ref": "bank-202608-salvage:q0170",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0170",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav2:m1-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "g = 12-(x)/(23) The equation shown gives the estimated amount of gas g, in gall…"
  },
  {
   "ref": "bank-202608-salvage:q0171",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0171",
   "subject": "math",
   "skill": "Linear functions",
   "tags": [
    "src:202608asiav2:m2-q5"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The table shows three values of x and their corresponding values of g(x), where…"
  },
  {
   "ref": "bank-202608-salvage:q0172",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0172",
   "subject": "math",
   "skill": "Linear inequalities in one or two variables",
   "tags": [
    "src:202608asiav3:m2-q15"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "y < -4x y \\ge 45 There are three points (-12, n), where n is an integer, that a…"
  },
  {
   "ref": "bank-202608-salvage:q0173",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0173",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav3:m2-q3"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the x‑ intercept of the graph of y=(28-x)/(ax+b) in the xy‑ plane, wher…"
  },
  {
   "ref": "bank-202608-salvage:q0174",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0174",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608asiav3:rw2-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0175",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0175",
   "subject": "rw",
   "skill": "Command of Evidence (Textual)",
   "tags": [
    "src:202608usv1:rw2-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which finding, if true, would most directly support the student’s claim?"
  },
  {
   "ref": "bank-202608-salvage:q0176",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0176",
   "subject": "math",
   "skill": "Circles",
   "tags": [
    "src:202608asiav4:m2-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "x^{2} + 16x + y^{2} = 12y + 101 In the xy-plane, the graph of the given equatio…"
  },
  {
   "ref": "bank-202608-salvage:q0177",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0177",
   "subject": "rw",
   "skill": "Inferences",
   "tags": [
    "src:202608usv1:rw2-q11"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most logically completes the text?"
  },
  {
   "ref": "bank-202608-salvage:q0178",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0178",
   "subject": "math",
   "skill": "One-variable data: Distributions and measures of center and spread",
   "tags": [
    "src:202608usv1:m1-q19"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The table shows the distribution of height, in centimeters, of 25 objects. Heig…"
  },
  {
   "ref": "bank-202608-salvage:q0179",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0179",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608usv1:m2-q12"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "y = 2 (x - d)(x + d)(x + g)(x - d) In the given equation, d and g are distinct…"
  },
  {
   "ref": "bank-202608-salvage:q0180",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0180",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608usv1:m2-q16"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the xy-plane, the graph of function f, where y = f(x), has exactly 8 x-inter…"
  },
  {
   "ref": "bank-202608-salvage:q0181",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0181",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav4:m2-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "t(v - 89) + t = w The given equation relates the positive numbers w, t, and v.…"
  },
  {
   "ref": "bank-202608-salvage:q0182",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0182",
   "subject": "math",
   "skill": "Two-variable data: Models and scatterplots",
   "tags": [
    "src:202608asiav1:m2-q8"
   ],
   "keyType": "mcq",
   "retired": true,
   "supersededBy": "q0205",
   "stemPreview": "Based on the graph, which of the following is closest to the predicted depth be…"
  },
  {
   "ref": "bank-202608-salvage:q0183",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0183",
   "subject": "rw",
   "skill": "Form, Structure, and Sense",
   "tags": [
    "src:202608asiav1:rw2-q20"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0184",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0184",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav2:m1-q6"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "(8y + 6) - (5y + 1) The given expression is equivalent to by + c, where b and c…"
  },
  {
   "ref": "bank-202608-salvage:q0185",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0185",
   "subject": "math",
   "skill": "Systems of two linear equations in two variables",
   "tags": [
    "src:202608asiav3:m2-q10"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Line j in the xy-plane passes through the points (9, 0) and (0, 6). Line k pass…"
  },
  {
   "ref": "bank-202608-salvage:q0186",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0186",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw1-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0187",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0187",
   "subject": "rw",
   "skill": "Boundaries",
   "tags": [
    "src:202608asiav3:rw2-q25"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice completes the text so that it conforms to the conventions of Stand…"
  },
  {
   "ref": "bank-202608-salvage:q0188",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0188",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m1-q13"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the x coordinate of the x- intercept of line k?"
  },
  {
   "ref": "bank-202608-salvage:q0189",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0189",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m1-q18"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which function gives the number of points awarded for a correct answer x second…"
  },
  {
   "ref": "bank-202608-salvage:q0190",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0190",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav1:m1-q21"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which equation correctly expresses v in terms of t and w?"
  },
  {
   "ref": "bank-202608-salvage:q0191",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0191",
   "subject": "math",
   "skill": "Linear functions",
   "tags": [
    "src:202608asiav1:m1-q22"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The table shows three values of x and their corresponding values of gx, where g…"
  },
  {
   "ref": "bank-202608-salvage:q0192",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0192",
   "subject": "math",
   "skill": "One-variable data: Distributions and measures of center and spread",
   "tags": [
    "src:202608asiav1:m2-q1"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "The table shows the frequency of each data value in a data set. Which data valu…"
  },
  {
   "ref": "bank-202608-salvage:q0193",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0193",
   "subject": "math",
   "skill": "Probability and conditional probability",
   "tags": [
    "src:202608asiav1:m2-q14"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If a sandwich is selected at random, which expression represents the probabilit…"
  },
  {
   "ref": "bank-202608-salvage:q0194",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0194",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m2-q15"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the value of h(4)?"
  },
  {
   "ref": "bank-202608-salvage:q0195",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0195",
   "subject": "math",
   "skill": "Linear equations in two variables",
   "tags": [
    "src:202608asiav1:m2-q16"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What is the slope of line k?"
  },
  {
   "ref": "bank-202608-salvage:q0196",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0196",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m2-q20"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "What was the population of this city in 1742?"
  },
  {
   "ref": "bank-202608-salvage:q0197",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0197",
   "subject": "math",
   "skill": "Ratios, rates, proportional relationships, and units",
   "tags": [
    "src:202608asiav1:m2-q7"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "A certain salmon shark can swim at a maximum speed of 16 meters per second. At…"
  },
  {
   "ref": "bank-202608-salvage:q0198",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0198",
   "subject": "math",
   "skill": "Equivalent expressions",
   "tags": [
    "src:202608asiav1:m2-q9"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which expression is equivalent to 240x² + 56?"
  },
  {
   "ref": "bank-202608-salvage:q0199",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0199",
   "subject": "math",
   "skill": "Nonlinear functions",
   "tags": [
    "src:202608asiav1:m1-q14"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "An equation of the graph shown is y = (-3/8) (x - p)² + 6, where p is an intege…"
  },
  {
   "ref": "bank-202608-salvage:q0200",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0200",
   "subject": "math",
   "skill": "Right triangles and trigonometry",
   "tags": [
    "src:202608asiav1:m1-q17"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In triangle PQR, the sine of angle Q is 1/2. What is the length of PQ?"
  },
  {
   "ref": "bank-202608-salvage:q0201",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0201",
   "subject": "math",
   "skill": "Lines, angles, and triangles",
   "tags": [
    "src:202608asiav1:m2-q12"
   ],
   "keyType": "spr",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "In the figure, lines m and n are parallel and line t intersects both lines. Wha…"
  },
  {
   "ref": "bank-202608-salvage:q0202",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0202",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw1-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "According to the graph, the lowest-priced nuts were _____ Which choice most eff…"
  },
  {
   "ref": "bank-202608-salvage:q0203",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0203",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw1-q12"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which consideration, if true, should make the farmer most hesitant to rely on w…"
  },
  {
   "ref": "bank-202608-salvage:q0204",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0204",
   "subject": "rw",
   "skill": "Command of Evidence (Quantitative)",
   "tags": [
    "src:202608asiav1:rw2-q10"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Which choice most effectively uses data from the table to complete the statemen…"
  },
  {
   "ref": "bank-202608-salvage:q0205",
   "containerType": "bank",
   "bankId": "bank-202608-salvage",
   "qid": "q0205",
   "subject": "math",
   "skill": "Two-variable data: Models and scatterplots",
   "tags": [
    "src:202608asiav1:m2-q8"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "Based on the graph, which of the following is closest to the predicted depth be…"
  },
  {
   "ref": "bank-david-core:q0001",
   "containerType": "bank",
   "bankId": "bank-david-core",
   "qid": "q0001",
   "subject": "math",
   "skill": "Linear equations in one variable",
   "tags": [
    "algebra",
    "linear-equations"
   ],
   "keyType": "mcq",
   "retired": false,
   "supersededBy": null,
   "stemPreview": "If 3(x-4)=18, what is the value of x?"
  }
 ]
};
